# Dependencies
highlighter:      rouge
markdown:         kramdown

kramdown:
  input: GFM

# Permalinks
permalink:        date
relative_permalinks: false

# Setup
title:            Benjamin Hmiel
tagline:          'Geoscience, Ph. D'
description:      ''
url:              http://benhmiel.github.io
baseurl:          /

author:
  name:           'Benjamin Hmiel'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/benhmiel/benhmiel.github.io
