# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Abe Hmiel
tagline:          'Data Goblin, Ph. D'
description:      ''
url:              http://abehmiel.github.io
baseurl:          /

author:
  name:           'Abe Hmiel'
  url:            https://twitter.com/unless_if

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/abehmiel/abehmiel.github.io
